### PR TITLE
Czech language translation

### PR DESCRIPTION
**Pull request by Piskvor**
The package only uses a few strings, and since I need it in Czech anyway, contributing it upstream. (Wonderful piece of software, saved me a lot of headache, thanks!)

### CODE REVIEW

**Comment by mateuszgachowski** [comment]
Im not sure if anyone is looking at those PRs - I've added Polish language some time ago and its still not commented / merged. Maybe its worth to do a fork of this project for now to have all new great features merged.

**Comment by FranDias** [comment]
Oh wow. I'm not super familiar with this project but I'll give it a look over and merge today or tomorrow (plus your other translation)

**Comment by FranDias** [comment]
just saw the other translations over a year old. Thanks for hanging with us

**Comment by mateuszgachowski** [comment]
Oh, so you are alive guys :)
Good to see that - yeah, I thought the project is abandoned but what a nice surprise :)

**Comment by FranDias** [comment]
Děkuji

Renders files and I sampled some translations via google translate. seems legit.

**Pull request merged**
