### PR TITLE
Create offline-language-persian-indicator.css

### PR DESCRIPTION
**Pull request by mamadoo**
Add support for Persian language

### CODE REVIEW

**Comment by adamschwartz** [comment]
Thanks @mamadoo. Would you possibly be able to add a language file for all of the content strings? 

Here’s French, e.g.: https://github.com/HubSpot/offline/blob/master/sass/_french.sass

**Comment by adamschwartz** [comment]
Thanks!

**Comment by mamadoo** [comment]
Thanks for your hint. _persian.sass added.

**Comment by adamschwartz** [comment]
:+1:

**Comment by mamadoo** [comment]
I should to add offline-language-persian.css too or don't need?

**Comment by adamschwartz** [comment]
yes, please. that would be great, thanks.

**Comment by mamadoo** [comment]
No problem.:+1:

**Pull request merged**
