### PR TITLE
Offline.options + AMD

### PR DESCRIPTION
**Pull request by matghaleb**
Offline.options can now be defined before including offline.js
setTimeout(init, 0) trick is not working using AMD so it will be particulary usefull in this case

### CODE REVIEW

**Comment by rawls238** [comment]
can you rebase this off master so we can merge this in?

**Comment by matghaleb** [comment]
it should be ok

**Comment by rawls238** [comment]
sorry but can you do it again, the transpiled javascript file is annoying.

**Comment by matghaleb** [comment]
is it ok for you ?

**Comment by rawls238** [comment]
yea looks good

**Pull request merged**
